# Use postgres/test user/password credentials
version: '3.1'

services:
  db:
    container_name: djormgo-js-test-db
    image: postgres:9-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: test
    ports:
       - "5432:5432"
